# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46696b9826c9c08aa14343fc9a5b0b3874f0c6676949909a21dd3a08b8b776573a41e96e0053014e9449362ef0c7efb350f37152a66f0abdd943f7144ce596cc

test:
  secret_key_base: ea822868844e766b460563e70a33132bc32a89d043cbbf9ef86744d97f83da61b54da408307660929d8d37fcc34be51c4e96a766ce78dc0d4b9d6d36f095f193

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
